# -*- coding: utf-8 -*-
"""
/***************************************************************************
 rasterinversor
                                 A QGIS plugin
 The plugin inverts the values of a raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-29
        copyright            : (C) 2018 by Sergio Carrera Fernández
        email                : scarreraf@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load rasterinversor class from file rasterinversor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_inversor import rasterinversor
    return rasterinversor(iface)
